include:
  - project: 'cyberfusion/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/debian-packages.yml'
      - '/python.yml'

variables:
  APTLY_BASE_REPOSITORY: common

stages:
  - test
  - build
  - publish

unit test:
  stage: test
  image: python:3.9
  script:
    - !reference [.add repositories, script]
    - apt-get -y install python3-cyberfusion-common python3-cached-property
    - echo "deb http://debmirror.tuxis.nl/debian $DEBIAN_CODENAME-backports main" >> /etc/apt/sources.list.d/backports.list
    - apt-get update
    - apt-get -y install borgbackup -t bullseye-backports
    - pip install --no-cache-dir -r requirements/test.txt
    - cp $CI_PROJECT_DIR/progress_file_with_known_types.txt /tmp/progress_file_with_known_types.txt
    - cp $CI_PROJECT_DIR/progress_file_with_unknown_types.txt /tmp/progress_file_with_unknown_types.txt
    - cp $CI_PROJECT_DIR/progress_file_with_no_lines.txt /tmp/progress_file_with_no_lines.txt
    - PYTHONPATH=$CI_PROJECT_DIR/src:/usr/lib/python3/dist-packages pytest -vvv --cov-branch --cov=cyberfusion.BorgSupport --cov-config=.coveragerc --cov-fail-under=100 --junitxml=report-pytest.xml
  artifacts:
    reports:
      junit: report-*.xml
