image: debian:buster

stages:
  - test
  - build

styling test:
  stage: test
  image: python:3.7
  script:
    - pip install --no-cache-dir -r requirements/dev.txt
    - mypy . --junit-xml report-mypy.xml
    - flake8 . --tee --output-file flake8.txt; exit_code=$?; flake8_junit flake8.txt report-flake8.xml
    - if [ $exit_code -ne 0 ]; then exit 1; fi;
    - isort -c .
    - black --check .
  artifacts:
    reports:
      junit: report-*.xml

unit test:
  stage: test
  image: python:3.7
  script:
    - echo 'deb https://deb.cyberfusion.nl/ stable main' > /etc/apt/sources.list.d/cyberfusion-packages.list
    - apt-key adv --fetch-keys https://deb.cyberfusion.nl/cfpkg.gpg
    - apt update
    - apt -y install python-cyberfusion-common
    - echo 'deb http://debmirror.tuxis.nl/debian buster-backports main' > /etc/apt/sources.list.d/backports.list
    - apt update
    - apt install -y borgbackup -t buster-backports
    - pip install --no-cache-dir -r requirements/test.txt
    - cp $CI_PROJECT_DIR/progress_file_with_known_types.txt /tmp/progress_file_with_known_types.txt
    - cp $CI_PROJECT_DIR/progress_file_with_unknown_types.txt /tmp/progress_file_with_unknown_types.txt
    - cp $CI_PROJECT_DIR/progress_file_with_no_lines.txt /tmp/progress_file_with_no_lines.txt
    # Use --maxfail=1 because almost all tests depend on each other's success
    - PYTHONPATH=$CI_PROJECT_DIR/src:/usr/lib/python3/dist-packages pytest -vvv --cov-branch --cov=cyberfusion.BorgSupport --cov-config=.coveragerc --cov-fail-under=95 --junitxml=report-pytest.xml --maxfail=1
  artifacts:
    reports:
      junit: report-*.xml

build test:
  stage: test
  script:
    - apt update
    - apt --no-install-recommends -y install apt-transport-https ca-certificates build-essential devscripts equivs gnupg lintian
    - echo 'deb https://deb.cyberfusion.nl/ stable main' > /etc/apt/sources.list.d/cyberfusion-packages.list
    - apt-key adv --fetch-keys https://deb.cyberfusion.nl/cfpkg.gpg
    - apt update
    - mk-build-deps -i -t 'apt -o Debug::pkgProblemResolver=yes --no-install-recommends -y'
    - dpkg-buildpackage -us -uc
    - dpkg-genchanges > ../pkg.changes
    - lintian --dont-check-part=manpages ../pkg.changes

build:
  stage: build
  only:
    - main
  script:
    - apt update
    - apt --no-install-recommends -y install apt-transport-https ca-certificates build-essential devscripts equivs gnupg
    - echo 'deb https://deb.cyberfusion.nl/ stable main' > /etc/apt/sources.list.d/cyberfusion-packages.list
    - apt-key adv --fetch-keys https://deb.cyberfusion.nl/cfpkg.gpg
    - apt update
    - mk-build-deps -i -t 'apt -o Debug::pkgProblemResolver=yes --no-install-recommends -y'
    - dpkg-buildpackage -us -uc
    - mkdir publish
    - cp ../*.deb publish/
  artifacts:
    paths:
      - publish/*.deb
    expire_in: 1 week
